Add lualine.nvim configuration example to README.md
dhruvasagar/vim-zoom pull request #30
Opened 2022-11-21 19:16 UTC by eggbean

This adds a configuration example for lualine.nvim.

2022-11-28 13:19 UTC, dhruvasagar requested changes

2022-11-28 13:19 UTC, dhruvasagar commented on README.md
> +- Fork it. Commit your changes and give your commit message some love.
Lets not change this

2022-11-28 13:19 UTC, dhruvasagar commented on README.md
> +```
perhaps ` ```lua` would be better

2022-11-28 13:26 UTC, eggbean commented
Sure. Sorry, but I'm not sure what I am supposed to do on github here 😳
How can I apply your changes or do I have to do it manually?

2022-12-01 14:37 UTC, merged

2022-12-01 14:38 UTC, dhruvasagar commented
@eggbean np, thanks for your contribution, I will make some of these minor changes myself.